# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:   # this is needed.  Don't remove it. Don't know what it does, though.  It is not Bootstrap CSS it seems.
  ps: Bootstrap

skip_branch_with_pr: true

environment:
  global:
    CRAN: http://cloud.r-project.org
    WARNINGS_ARE_ERRORS: 1
    R_CHECK_ARGS: --as-cran --no-manual
# --no-manual to avoid error 'pdflatex is not available'
# --as-cran no longer a lot slower (now takes under 6 mins with and without); logs show _R_CHECK_CRAN_INCOMING_=FALSE which could take 5+ mins
    _R_CHECK_NO_STOP_ON_TEST_ERROR_: true
# continue tests even if some script failed
    _R_CHECK_TESTS_NLINES_: 0
# Block truncation of any error messages in R CMD check
# R is 64-bit only on Windows from 4.2.0 (prior default was build and test both 32bit and 64bit) so we no longer use R_ARCH to pick one to reduce CI time in PRs

  matrix:

  - R_VERSION: release  # the single Windows.zip binary (both 32bit/64bit) that users following dev version of installation instructions should click

#  - R_VERSION: devel   # Never turn back on. GLCI after merge covers latest daily R-devel very well, so we shouldn't confuse and slow down PR dev cycle by measuring PRs against daily R-devel too. If a change in R-devel yesterday breaks the PR, it's very unlikely to be due to something in the PR. So we should accept the PR if it passes R-release and fix separately anything related to R-devel which we'll see from GLCI.

before_build:
  - cmd: ECHO no Revision metadata added to DESCRIPTION
  #translate from unix: - cmd: ECHO "Revision:" $CI_BUILD_REF >> ./DESCRIPTION

build_script:
  - set _R_CHECK_FORCE_SUGGESTS_=false
# Include the subset of Suggests that test.data.table() has tests for :
  - travis-tool.sh r_install bit64
  - travis-tool.sh r_install xts
  - travis-tool.sh r_install nanotime
  - travis-tool.sh r_install R.utils
  - travis-tool.sh r_install yaml

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
