language: r
dist: trusty
sudo: required
cache: packages
warnings_are_errors: true

branches:
  only:
    - "master"

r:
  - release

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include"; fi

r_packages:
  - covr      # used for code coverage reports in github pull requests
  - drat      # used in deploy.sh to publish tar.gz to github.io/Rdatatable/data.table
  - devtools  # explicitly named temp fix for #2801

before_script:
  - echo "Revision:" $TRAVIS_COMMIT >> ./DESCRIPTION

after_success:
  - travis_wait Rscript -e 'library(covr); codecov()'
  - test $TRAVIS_REPO_SLUG == "Rdatatable/data.table" &&
    test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - PKG_CFLAGS="-O3 -Wall -pedantic"
    - _R_CHECK_NO_STOP_ON_TEST_ERROR_=true
    - _R_CHECK_CRAN_INCOMING_REMOTE_=false
    # drat using @jangorecki token
    - secure: "CxDW++rsQApQWos+h1z/F76odysyD6AtXJrDwlCHlgqXeKJNRATR4wZDDR18SK+85jUqjoqOvpyrq+5kKuyg6AnA/zduaX2uYE5mcntEUiyzlG/jJUKbcJqt22nyAvFXP3VS60T2u4H6IIhVmr7dArdxLkv8W+pJvf2Tg6kx8Ws="
