# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki
# 
# Hack for 'error on warning' except when the warning is about vignette pdfs/html
# Thanks to csgillespie for https://github.com/csgillespie/travis-examples/tree/master/bioconductor
language: c
sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sed "s/grep -q WARNING/grep WARNING \| grep -v inst\/doc \| grep -v 'Status:.*WARNING'/" travis-tool.sh > ./tmp.sh
  - mv tmp.sh travis-tool.sh
  - chmod 755 ./travis-tool.sh  
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh bioc_install IRanges
  - ./travis-tool.sh bioc_install GenomicRanges
  # - ./travis-tool.sh r_binary_install caret
  - ./travis-tool.sh install_deps
  
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - ./travis-tool.sh install_github jimhester/covr
  - Rscript -e 'library(covr);codecov()'
  - ./travis-tool.sh install_github eddelbuettel/drat
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - PKG_CFLAGS="-g -O3 -Wall -pedantic"
    - WARNINGS_ARE_ERRORS=1
    # drat using @jangorecki token
    - secure: "FilvtH+HCm0TJEAQSQHu5H1l+nYqgHqe+qwnF/iJfCMPc7RanGWSqKtgd3MU3S1nSvXUXS1AkJmExs4+v+m+02MutkpTiVW5RChUnhgjPi0zFCJv/TPtgi+DHwE6T+JJtd1GBsNoG3K+mzSjOqibpygUgYG1+C7eID0+/o6UlJU="
