language: r
dist: bionic
cache: packages   # to rebuild cache see tweet thread ending here https://twitter.com/jimhester_/status/1115718589804421121
warnings_are_errors: true

r:
  - release

os:
  - linux
  - osx  # Takes 13m (+9m linux = 22m total); #3357; #3326; #3331. When off it's to speed up dev cycle; CRAN_Release.cmd has a reminder to turn back on.

brew_packages:
  - llvm

r_packages:
  - drat      # used in .ci/deploy.sh to publish tar.gz to github.io/Rdatatable/data.table
  - covr

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm "/usr/local/bin/gfortran"; fi

before_script:
  - echo "Revision:" $TRAVIS_COMMIT >> ./DESCRIPTION

after_success:
  - test $TRAVIS_OS_NAME == "linux" &&
    travis_wait Rscript -e 'library(covr); codecov()'
  - test $TRAVIS_OS_NAME == "linux" &&
    test $TRAVIS_REPO_SLUG == "Rdatatable/data.table" &&
    test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    bash .ci/deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - PKG_CFLAGS="-O3 -Wall -pedantic"
    - _R_CHECK_NO_STOP_ON_TEST_ERROR_=true
    - _R_CHECK_CRAN_INCOMING_REMOTE_=false
    # Block truncation of any error messages in R CMD check
    - _R_CHECK_TESTS_NLINES_=0
    # drat using @jangorecki token
    - secure: "CxDW++rsQApQWos+h1z/F76odysyD6AtXJrDwlCHlgqXeKJNRATR4wZDDR18SK+85jUqjoqOvpyrq+5kKuyg6AnA/zduaX2uYE5mcntEUiyzlG/jJUKbcJqt22nyAvFXP3VS60T2u4H6IIhVmr7dArdxLkv8W+pJvf2Tg6kx8Ws="
