# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

environment:
  global:
    CRAN: http://cloud.r-project.org/
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true
    R_CHECK_ARGS: --no-manual
# R_CHECK_ARGS specified in order to turn off --as-cran (on by default) as that can be slow
    R_ARCH: x64
# multiarch is on by default which runs tests on both 32bit R and 64bit R in one x64 job; i.e. very nice and convenient for all.
# The default for R_ARCH is i386, though, for which multiarch would just compile and test 32bit, hence setting R_ARCH to x64
    GCC_PATH: mingw_64
# Default GCC_PATH appears to be gcc-4.6.3 which is now unsupported as from Rtools.exe v3.4.

  matrix:

  - R_VERSION: release  # the single Windows.zip binary (both 32bit/64bit) that users following dev version of installation instructions should click

  - R_VERSION: devel

before_build:
  - cmd: ECHO Revision: $Env:APPVEYOR_REPO_COMMIT>>DESCRIPTION

build_script:
  - set _R_CHECK_FORCE_SUGGESTS_=false
# R-devel needs packages recompiled as from 12 Sep 2017
# Guessing that was the cause of knitr causing AppVeyor R-devel checks to fail
# Commenting out these for now so at least the rest of data.table is checked on R-devel on Windows
#  - travis-tool.sh r_install bit64
#  - travis-tool.sh r_install fastmatch
#  - travis-tool.sh r_install knitr
#  - travis-tool.sh r_install nanotime

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
