on:
  push:
    branches:
     - master
  pull_request:
    branches:
     - master

name: code-quality

jobs:
  lint-r:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            r-lib/lintr
            local::.
          needs: lint

      - name: Lint
        run: lintr::lint_package(pattern = "(?i)[.](r|rmd)$") # TODO(#5830): use the default pattern
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
          R_LINTR_LINTER_FILE: .ci/.lintr
  lint-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Lint
        run: |
          linter_env = new.env()
          for (f in list.files('.ci/linters/c', full.names=TRUE)) sys.source(f, linter_env)
          for (f in list.files('src', pattern='[.][ch]$', full.names=TRUE)) {
            c_obj = list(path = f, lines = readLines(f))
            c_obj$preprocessed = system2("gcc", c("-fpreprocessed", "-E", "-xc", "-", f), stdout=TRUE, stderr=FALSE)
            for (linter in ls(linter_env)) linter_env[[linter]](c_obj)
            # TODO(#6272): Incorporate more checks from CRAN_Release
          }
        shell: Rscript {0}
